### ISSUE TITLE
V-wave causes vue-test-utils to fail mounting

### ISSUE THREAD

**Issue by Victor-R** [justintaddei/v-wave#47]
### Problem:
I'm trying to write a test with a component that uses v-wave directive, but when  I try to mount it with `shallowMount()` or `mount()` the same error happens:

Test:
```
describe("Components: TemplateCard", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });
  it("should get correct icon class when the type is", () => {
    const wrapper = shallowMount(TemplateCard, {
      global: { stubs: ["router-link"], plugins: [VWave] },
      props: {
        template: mockedTemplate
      }
    });

    console.log(wrapper.html());
  });
  it("should get template Models array", () => {
    const wrapper = shallowMount(TemplateCard, {
      global: { stubs: ["router-link"], plugins: [VWave] },
      props: {
        template: mockedTemplate
      }
    });

    const modelsArray = wrapper.vm.content;

    expect(modelsArray).toEqual(mockedTemplate.templateContentResponses);
  });
});
```
Error:
![image](https://user-images.githubusercontent.com/12578575/109878303-dead6480-7c52-11eb-8fd3-6a0596f9454b.png)

I tried to add v-wave as a plugin, that makes the first test pass for some reason. Am I doing something wrong?

**Comment by justintaddei** [comment]
This is very likely related to #46 

I'm actively working on it and will get back to you soon.

**Comment by justintaddei** [comment]
Can you tell what object `created` is supported to be a property of?

Also, are you using Vue 2 or Vue 3?

**Comment by Victor-R** [comment]
@justintaddei I'm using vue 3 (^3.0.6) and vue-test-utils (^2.0.0-rc.2).

The property 'created' seams to be from vue core. I did not found it, maybe is something related with the lifecycle 'created'?
```
Components: TemplateCard › should get template Models array

    TypeError: Cannot read property 'created' of undefined

      94 |
      95 |   it("should get template Models array", () => {
    > 96 |     const wrapper = mount(TemplateCard, {
         |                     ^
      97 |       global: { stubs: ["router-link"], plugins: [VWave] },
      98 |       props: {
      99 |         template: mockedTemplate

      at invokeDirectiveHook (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2901:33)
      at mountElement (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3788:17)
      at processElement (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3767:13)
      at patch (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3687:21)
      at mountChildren (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3862:13)
      at mountElement (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3785:17)
      at processElement (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3767:13)
      at patch (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3687:21)
      at componentEffect (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4178:21)
      at reactiveEffect (node_modules/@vue/reactivity/dist/reactivity.cjs.js:46:24)
      at Object.effect (node_modules/@vue/reactivity/dist/reactivity.cjs.js:21:9)
      at setupRenderEffect (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4143:38)
      at mountComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4102:9)
      at processComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4062:17)
      at patch (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3690:21)
      at componentEffect (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4178:21)
      at reactiveEffect (node_modules/@vue/reactivity/dist/reactivity.cjs.js:46:24)
      at Object.effect (node_modules/@vue/reactivity/dist/reactivity.cjs.js:21:9)
      at setupRenderEffect (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4143:38)
      at mountComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4102:9)
      at processComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4062:17)
      at patch (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3690:21)
      at render (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4763:13)
      at mount (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3033:25)
      at Object.app.mount (node_modules/@vue/runtime-dom/dist/runtime-dom.cjs.js:1222:23)
      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:2335:18)
      at Object.<anonymous> (src/components/tests/templateCard.spec.ts:96:21)
```

**Comment by justintaddei** [comment]
You're probably right about it being a life cycle hook considering the next function in the stack is `invokeDirectiveHook`.

I'll likely be reworking a lot of the internals to address the aforementioned issue. I have a feeling that whatever I come up with will resolve this too.

**Comment by justintaddei** [comment]
Please try installing [v-wave@beta](https://www.npmjs.com/package/v-wave/v/1.2.9-beta.0) (`npm i v-wave@beta`) and let me know if it resolves your issue. I've changed how v-wave detects a vue3 environment and it shouldn't cause this problem anymore.
