### ISSUE TITLE
Changing directive's name in Nuxt 3

### ISSUE THREAD

**Issue by DamianGlowala** [justintaddei/v-wave#597]
Could it be possible to change the directive's name in Nuxt 3, please? v2.0.0 doesn't seem to allow it.

**Comment by DamianGlowala** [comment]
Looked at the code and yes, I agree this is actually possible! Initially thought so because of the lack of types/autocompletion for the module options. Do you think it would be possible to add these for better DX?

**Comment by justintaddei** [comment]
Absolutely. I'll review and get it published on Monday if everything looks good. I'd do it this weekend but I'm away at grandparents' and won't have time :)

**Comment by justintaddei** [comment]
@DamianGlowala the PR broke my local Nuxt 3 test project so I decided to revert it for now. I'll take another look sometime this week.

```sh
 ERROR  Cannot start nuxt:  Cannot find module 'C:/dev/npm/_examples/v-wave-example/v-wave/nuxt'                                                                                                         10:29:41 AM  
Require stack:
- C:\dev\npm\_examples\v-wave-example\index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
  at Function.resolve (node:internal/modules/helpers:187:19)
  at Function._resolve [as resolve] (node_modules\jiti\dist\jiti.js:1:251148)
  at resolveModule (/C:/dev/npm/_examples/v-wave-example/node_modules/@nuxt/kit/dist/index.mjs:2239:29)
  at requireModule (/C:/dev/npm/_examples/v-wave-example/node_modules/@nuxt/kit/dist/index.mjs:2244:24)
  at loadNuxtModuleInstance (/C:/dev/npm/_examples/v-wave-example/node_modules/@nuxt/kit/dist/index.mjs:2472:90)
  at async installModule (/C:/dev/npm/_examples/v-wave-example/node_modules/@nuxt/kit/dist/index.mjs:2438:47)
  at async initNuxt (/C:/dev/npm/_examples/v-wave-example/node_modules/nuxt/dist/index.mjs:3702:7)
  at async NuxtDevServer._load (/C:/dev/npm/_examples/v-wave-example/node_modules/nuxi/dist/chunks/dev2.mjs:255:5)
  at async NuxtDevServer.load (/C:/dev/npm/_examples/v-wave-example/node_modules/nuxi/dist/chunks/dev2.mjs:187:7)
```

**Comment by justintaddei** [comment]
I haven't found a solution for this yet. I definitely want to include it but I'll have to revisit it when I have more time

**Comment by Rasool-deldar** [comment]
> I haven't found a solution for this yet. I definitely want to include it but I'll have to revisit it when I have more time

Thank you very much. Please add this item. It is really useful 😊💕

**Comment by justintaddei** [comment]
Resolved by https://github.com/justintaddei/v-wave/commit/d1d0115379ab6dccc994ea4d7bb5fdd141b2e17e
